# Generated by Django 5.0.4 on 2024-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "telegram_id",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("wishes", models.CharField(max_length=100)),
                ("room", models.PositiveIntegerField(blank=True, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("gifts_to", models.IntegerField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
