# Generated by Django 5.0.4 on 2024-04-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secret_santa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_giver",
            field=models.BooleanField(default=False),
        ),
    ]
