# Generated by Django 5.0.4 on 2024-04-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secret_santa", "0002_user_has_giver"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_priority",
            field=models.IntegerField(default=0),
        ),
    ]
